//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { usersEntity } from './db/users.entity';
import { departmentsEntity } from './db/departments.entity';
import { initiativesEntity } from './db/initiatives.entity';
import { goalsEntity } from './db/goals.entity';
import { emissionSourcesEntity } from './db/emissionSources.entity';
import { resourceUsageEntity } from './db/resourceUsage.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      usersEntity,
      departmentsEntity,
      initiativesEntity,
      goalsEntity,
      emissionSourcesEntity,
      resourceUsageEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      users: [
        {
          userName: 'userName 1',
          department: 1,
          password: 'password 1',
          email: 'email 1',
          id: 27,
        },
        {
          userName: 'userName 2',
          department: 2,
          password: 'password 2',
          email: 'email 2',
          id: 27,
        },
        {
          userName: 'userName 3',
          department: 3,
          password: 'password 3',
          email: 'email 3',
          id: 20,
        },
        {
          userName: 'userName 4',
          department: 4,
          password: 'password 4',
          email: 'email 4',
          id: 9,
        },
        {
          userName: 'userName 5',
          department: 5,
          password: 'password 5',
          email: 'email 5',
          id: 25,
        },
      ],
      departments: [
        { departmentName: 'departmentName 1', departmentHead: 1, id: 33 },
        { departmentName: 'departmentName 2', departmentHead: 2, id: 17 },
        { departmentName: 'departmentName 3', departmentHead: 3, id: 25 },
        { departmentName: 'departmentName 4', departmentHead: 4, id: 3 },
        { departmentName: 'departmentName 5', departmentHead: 5, id: 91 },
      ],
      initiatives: [
        {
          name: 'name 1',
          description: 'description 1',
          startDate: '2024-09-03T01:12:23.533Z',
          endDate: '2024-12-11T16:36:40.550Z',
          relatedDepartment: 1,
          status: 'status 1',
          id: 45,
        },
        {
          name: 'name 2',
          description: 'description 2',
          startDate: '2023-07-25T11:06:19.889Z',
          endDate: '2024-11-03T16:10:47.456Z',
          relatedDepartment: 2,
          status: 'status 2',
          id: 39,
        },
        {
          name: 'name 3',
          description: 'description 3',
          startDate: '2023-11-20T21:54:20.489Z',
          endDate: '2025-01-17T18:49:30.265Z',
          relatedDepartment: 3,
          status: 'status 3',
          id: 31,
        },
        {
          name: 'name 4',
          description: 'description 4',
          startDate: '2024-01-06T20:25:53.286Z',
          endDate: '2024-11-02T12:59:34.386Z',
          relatedDepartment: 4,
          status: 'status 4',
          id: 78,
        },
        {
          name: 'name 5',
          description: 'description 5',
          startDate: '2024-04-16T23:26:41.515Z',
          endDate: '2023-10-30T01:52:32.060Z',
          relatedDepartment: 5,
          status: 'status 5',
          id: 65,
        },
      ],
      goals: [
        {
          name: 'name 1',
          description: 'description 1',
          targetDate: '2024-08-05T23:58:37.147Z',
          relatedDepartment: 1,
          status: 'status 1',
          id: 13,
        },
        {
          name: 'name 2',
          description: 'description 2',
          targetDate: '2023-05-04T12:12:44.385Z',
          relatedDepartment: 2,
          status: 'status 2',
          id: 51,
        },
        {
          name: 'name 3',
          description: 'description 3',
          targetDate: '2025-04-01T17:01:48.701Z',
          relatedDepartment: 3,
          status: 'status 3',
          id: 12,
        },
        {
          name: 'name 4',
          description: 'description 4',
          targetDate: '2024-05-23T23:16:08.409Z',
          relatedDepartment: 4,
          status: 'status 4',
          id: 68,
        },
        {
          name: 'name 5',
          description: 'description 5',
          targetDate: '2023-10-10T09:49:47.861Z',
          relatedDepartment: 5,
          status: 'status 5',
          id: 40,
        },
      ],
      emissionSources: [
        {
          sourceType: 'sourceType 1',
          quantityUsed: 0.81,
          emissionFactors: 0.46,
          totalEmissions: 0.44,
          id: 52,
        },
        {
          sourceType: 'sourceType 2',
          quantityUsed: 0.17,
          emissionFactors: 0.58,
          totalEmissions: 0.92,
          id: 48,
        },
        {
          sourceType: 'sourceType 3',
          quantityUsed: 0.75,
          emissionFactors: 0.49,
          totalEmissions: 0.73,
          id: 80,
        },
        {
          sourceType: 'sourceType 4',
          quantityUsed: 0.62,
          emissionFactors: 0.71,
          totalEmissions: 0.85,
          id: 77,
        },
        {
          sourceType: 'sourceType 5',
          quantityUsed: 0.71,
          emissionFactors: 0.65,
          totalEmissions: 0.99,
          id: 37,
        },
      ],
      resourceUsage: [
        {
          resourceType: 'resourceType 1',
          quantityConsumed: 0.32,
          unitOfMeasurement: 'unitOfMeasurement 1',
          periodOfConsumption: '2024-02-19T13:06:54.570Z',
          id: 17,
        },
        {
          resourceType: 'resourceType 2',
          quantityConsumed: 0.15,
          unitOfMeasurement: 'unitOfMeasurement 2',
          periodOfConsumption: '2025-01-24T08:27:15.016Z',
          id: 90,
        },
        {
          resourceType: 'resourceType 3',
          quantityConsumed: 0.22,
          unitOfMeasurement: 'unitOfMeasurement 3',
          periodOfConsumption: '2024-08-26T03:41:56.857Z',
          id: 72,
        },
        {
          resourceType: 'resourceType 4',
          quantityConsumed: 0.28,
          unitOfMeasurement: 'unitOfMeasurement 4',
          periodOfConsumption: '2024-12-05T13:34:50.305Z',
          id: 30,
        },
        {
          resourceType: 'resourceType 5',
          quantityConsumed: 0.66,
          unitOfMeasurement: 'unitOfMeasurement 5',
          periodOfConsumption: '2024-03-02T16:16:15.104Z',
          id: 52,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('usersEntity', data.users);
      await this.SeedResource('departmentsEntity', data.departments);
      await this.SeedResource('initiativesEntity', data.initiatives);
      await this.SeedResource('goalsEntity', data.goals);
      await this.SeedResource('emissionSourcesEntity', data.emissionSources);
      await this.SeedResource('resourceUsageEntity', data.resourceUsage);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
